# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box="zefirnikolov/AlmaLinux-8.7-minimal"
    jenkins.vm.hostname = "jenkins.do1.lab"
    jenkins.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    jenkins.vm.network "private_network", ip: "192.168.99.101"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.synced_folder ".", "/vagrant"
    jenkins.vm.provision "shell", path: "add_hosts.sh"
	  jenkins.vm.provision "shell", path: "install_jenkins.sh"
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box = "zefirnikolov/AlmaLinux-8.7-minimal"
    docker.vm.hostname = "docker.do1.lab"
    docker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
    end
    docker.vm.network "private_network", ip: "192.168.99.102"
    docker.vm.provision "shell", path: "add_hosts.sh"
	  docker.vm.provision "shell", path: "install_docker.sh"
  end
  
end
